name: Release

on:
  push:
    branches:
      - develop

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Build Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
        
      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install Dependencies
        run: yarn

      - name: Build packages
        run: yarn build

      - name: Extract packages
        run: |
          npm i medusa-dev-cli -g
          medusa-dev --set-path-to-repo `pwd`
          mkdir -p output_medusa
          cd output_medusa
          echo "-----------Cleaning Output Directory------------"
          rm -rf ./*
          cp ../sample_package.json package.json
          echo "-----------Setup Yarn Version------------"
          yarn set version 1.22.19
          timeout 10m medusa-dev || exit 0
          cd ..

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: medusa-artifact
          path: output_medusa/
